import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav/Nav";
import Footer from "./components/footer/Footer";
import 'bootstrap/dist/css/bootstrap.css';
import { ToastContainer} from 'react-toastify';
import CartProvider from "./context/index";
import 'react-toastify/dist/ReactToastify.css'; // Import styles
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Ecomm App With Next And Typescript",
  description: "Generated by Julnar Nabeel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} d-flex flex-column min-vh-100`}>
        <CartProvider>
          <Nav />
          <main className="flex-grow-1">
            <div className="container-fluid">
              {children}
            </div>
          </main>
          <Footer />
          <ToastContainer /> {/* Render the ToastContainer to display toasts to be availble in all components*/}
        </CartProvider>
      </body>
    </html>
  );
}
